services:
  frontend:
    image: paulomoro/pandora-front:latest
    container_name: pandora_frontend
    expose:
      - "80"
    environment:
      - VITE_API_URL=https://api.project-pandora.com.br
    networks:
      - pandora_net

networks:
  pandora_net:
    external: true
