name: 🏗️ Build Pandora Frontend Image

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Build da imagem
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USER }}/pandora-front
          COMMIT_SHA=${{ github.sha }}
          docker build -t $IMAGE_NAME:$COMMIT_SHA -t $IMAGE_NAME:${{ github.sha }}
 .

      - name: Push da imagem
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USER }}/pandora-front
          COMMIT_SHA=${{ github.sha }}
          docker push $IMAGE_NAME:$COMMIT_SHA
          docker push $IMAGE_NAME:${{ github.sha }}

