name: 🚀 CI/CD Pandora Frontend

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        env:
          REACT_APP_API_URL: ${{ vars.REACT_APP_API_URL }}
          FRONTEND_PORT: ${{ vars.FRONTEND_PORT }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          envs: REACT_APP_API_URL,FRONTEND_PORT
          script: |
            set -e
            cd /home/ubuntu/
            rm -rf pandora-front
            # Cria a rede externa se ainda não existir
            if ! docker network inspect pandora_net >/dev/null 2>&1; then
              echo "🔧 Criando rede externa 'pandora_net'..."
              docker network create pandora_net
            else
              echo "✅ Rede 'pandora_net' já existe"
            fi

            GIT_SSH_COMMAND="ssh -i ~/.ssh/pandora_frontend" \
            echo "📦 Clonando repositório do frontend..."
            git clone git@github.com:Laboratorio-de-Analise-de-Dados/pandora-front.git
            cd pandora-front
            git checkout main

            echo "⚙️ Subindo frontend com Docker Compose..."
            docker compose -f docker-compose.yml up -d --build

            echo "🧹 Limpando diretório..."
            cd ..
            rm -rf pandora-front

            echo "✅ Deploy do frontend concluído!"
