name: 🚀 Deploy Pandora Frontend

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            cd /home/ubuntu/

            echo "🧹 Limpando deploy antigo..."
            rm -rf pandora-frontend

            echo "📥 Clonando repositório..."
            git clone git@github.com:Laboratorio-de-Analise-de-Dados/pandora-front.git pandora-frontend
            cd pandora-frontend

            echo "⚙️ Subindo containers..."
            docker compose -f docker-compose.yml up -d

            echo "🧹 Removendo pasta do repositório..."
            cd ..
            rm -rf pandora-frontend

            echo "✅ Deploy concluído!"
